Reproduce bug
```
ProcessMembershipWorker
  #perform
    ambassador membership
      when sending a membership intvitation
        does not create ambassador_task_assignments (FAILED - 1)

Failures:

  1) ProcessMembershipWorker#perform ambassador membership when sending a membership intvitation does not create ambassador_task_assignments
     Failure/Error: ambassador = membership.user.becomes(Ambassador)

     NoMethodError:
       undefined method `becomes' for nil:NilClass
     # ./app/workers/process_membership_worker.rb:54:in `assign_all_ambassador_tasks_to'
     # ./app/workers/process_membership_worker.rb:20:in `perform'
     # ./spec/workers/process_membership_worker_spec.rb:15:in `block (6 levels) in <top (required)>'
     # ./spec/workers/process_membership_worker_spec.rb:14:in `block (5 levels) in <top (required)>'
     # -e:1:in `<main>'
```