Update bootstrap gem
pg gem upgrade limited by:

```
Bundler: failed to load command: unicorn_rails (ruby/2.5.1/bin/unicorn_rails)
LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).

ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/connection_handling.rb:50:in `establish_connection'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/railtie.rb:122:in `block (2 levels) in <class:Railtie>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:44:in `each'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/base.rb:315:in `<module:ActiveRecord>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-4.2.11/lib/active_record/base.rb:26:in `<top (required)>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/doorkeeper-3.1.0/lib/doorkeeper/orm/active_record/access_grant.rb:2:in `<module:Doorkeeper>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/doorkeeper-3.1.0/lib/doorkeeper/orm/active_record/access_grant.rb:1:in `<top (required)>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `block in require'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:274:in `require'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/doorkeeper-3.1.0/lib/doorkeeper/orm/active_record.rb:5:in `initialize_models!'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/doorkeeper-3.1.0/lib/doorkeeper/config.rb:37:in `setup_orm_models'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/doorkeeper-3.1.0/lib/doorkeeper/config.rb:11:in `configure'
~/Work/bike_index/config/initializers/doorkeeper.rb:18:in `<top (required)>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `block in load'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:240:in `load_dependency'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/dependencies.rb:268:in `load'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:652:in `block in load_config_initializer'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-4.2.11/lib/active_support/notifications.rb:166:in `instrument'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:651:in `load_config_initializer'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:615:in `each'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/engine.rb:615:in `block in <class:Engine>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `each'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:44:in `tsort_each_child'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `call'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:415:in `each_strongly_connected_component_from'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `call'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
ruby/2.5.1/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
~/Work/bike_index/config/environment.rb:8:in `<top (required)>'
config.ru:18:in `require'
config.ru:18:in `block in <main>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `instance_eval'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rack-1.6.11/lib/rack/builder.rb:55:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn.rb:54:in `eval'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn.rb:54:in `block in builder'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/bin/unicorn_rails:139:in `block in rails_builder'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:794:in `build_app!'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:659:in `init_worker_process'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:681:in `worker_loop'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:548:in `spawn_missing_workers'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:562:in `maintain_worker_count'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/lib/unicorn/http_server.rb:295:in `join'
ruby/2.5.1/lib/ruby/gems/2.5.0/gems/unicorn-5.5.1/bin/unicorn_rails:209:in `<top (required)>'
ruby/2.5.1/bin/unicorn_rails:23:in `load'
ruby/2.5.1/bin/unicorn_rails:23:in `<top (required)>'

```